#!/usr/bin/env python3
"""Regenerate strip/width_table.mbt from the Unicode character database.

A terminal gives every character a whole number of columns, and which number it
is comes straight from two UCD files: EastAsianWidth.txt decides what is two
columns wide, and DerivedGeneralCategory.txt decides what takes none (combining
marks and format characters). Encoding that by hand would be a guess, so the
table is generated and the script is kept next to it.

    python scripts/gen_width.py [--version 16.0.0]

Downloads are cached under scripts/.ucd so a rerun is offline.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent
CACHE = ROOT / ".ucd"
OUT = ROOT.parent / "strip" / "width_table.mbt"

FILES = {
    "EastAsianWidth.txt": "https://www.unicode.org/Public/{v}/ucd/EastAsianWidth.txt",
    "DerivedGeneralCategory.txt": "https://www.unicode.org/Public/{v}/ucd/extracted/DerivedGeneralCategory.txt",
}

LINE = re.compile(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*(\S+)")


def fetch(name: str, version: str) -> str:
    CACHE.mkdir(exist_ok=True)
    cached = CACHE / f"{version}-{name}"
    if not cached.exists():
        url = FILES[name].format(v=version)
        with urllib.request.urlopen(url, timeout=60) as response:
            cached.write_bytes(response.read())
    return cached.read_text(encoding="utf-8")


def ranges(text: str, wanted: set[str]) -> list[tuple[int, int]]:
    found: list[tuple[int, int]] = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        match = LINE.match(line)
        if not match or match.group(3) not in wanted:
            continue
        low = int(match.group(1), 16)
        high = int(match.group(2), 16) if match.group(2) else low
        found.append((low, high))
    return merge(found)


def merge(items: list[tuple[int, int]]) -> list[tuple[int, int]]:
    items.sort()
    out: list[tuple[int, int]] = []
    for low, high in items:
        if out and low <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], high))
        else:
            out.append((low, high))
    return out


def emit(name: str, doc: str, items: list[tuple[int, int]]) -> str:
    rows = "\n".join(f"  ({low}, {high})," for low, high in items)
    return (
        "///|\n"
        f"/// {doc}\n"
        f"let {name} : Array[(Int, Int)] = [\n{rows}\n]\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default="16.0.0")
    args = parser.parse_args()

    eaw = fetch("EastAsianWidth.txt", args.version)
    gc = fetch("DerivedGeneralCategory.txt", args.version)

    wide = ranges(eaw, {"W", "F"})
    # Mn and Me are combining marks that sit on the previous character; Cf is
    # invisible formatting, which includes the joiners emoji sequences use.
    zero = ranges(gc, {"Mn", "Me", "Cf"})

    body = [
        "// Copyright 2026 Leo Cheng",
        "// SPDX-License-Identifier: Apache-2.0",
        "",
        f"// Generated by scripts/gen_width.py from Unicode {args.version}. Do not edit.",
        "",
        emit(
            "wide",
            "Code points the East Asian Width property calls Wide or Fullwidth,"
            " each of which occupies two terminal columns.",
            wide,
        ),
        emit(
            "zero",
            "Combining marks and format characters, which occupy no column of"
            " their own.",
            zero,
        ),
    ]
    OUT.write_text("\n".join(body), encoding="utf-8")
    print(f"{OUT}: {len(wide)} wide ranges, {len(zero)} zero-width ranges")


if __name__ == "__main__":
    main()
